-- ------------------------- info -------------------------
-- @@ver: 1_000_000
-- @@info: 初始化fa-im模块
-- ------------------------- info -------------------------

-- ----------------------------
-- Table structure for im_conversation
-- ----------------------------
CREATE TABLE IF NOT EXISTS "im_conversation" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "type" smallint NOT NULL,
  "title" varchar(255) NULL DEFAULT NULL,
  "user_ids" text NULL,
  "cover" text NULL,
  "last_msg" varchar(255) NULL DEFAULT NULL,
  "manager_id" varchar(32) NULL DEFAULT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) NULL DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) NULL DEFAULT NULL,
  "upd_name" varchar(255) NULL DEFAULT NULL,
  "upd_host" varchar(255) NULL DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "im_conversation" IS 'IM-会话表';
COMMENT ON COLUMN "im_conversation"."id" IS 'ID';
COMMENT ON COLUMN "im_conversation"."type" IS '类型：1-单聊/2-群聊';
COMMENT ON COLUMN "im_conversation"."title" IS '群聊名称';
COMMENT ON COLUMN "im_conversation"."user_ids" IS '聊天用户ID集合';
COMMENT ON COLUMN "im_conversation"."cover" IS '封面图标';
COMMENT ON COLUMN "im_conversation"."last_msg" IS '最新一条消息';
COMMENT ON COLUMN "im_conversation"."manager_id" IS '管理员ID';
COMMENT ON COLUMN "im_conversation"."crt_time" IS '创建时间';
COMMENT ON COLUMN "im_conversation"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "im_conversation"."crt_name" IS '创建用户';
COMMENT ON COLUMN "im_conversation"."crt_host" IS '创建IP';
COMMENT ON COLUMN "im_conversation"."upd_time" IS '更新时间';
COMMENT ON COLUMN "im_conversation"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "im_conversation"."upd_name" IS '更新用户';
COMMENT ON COLUMN "im_conversation"."upd_host" IS '更新IP';
COMMENT ON COLUMN "im_conversation"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "im_conversation__upd_time" ON "im_conversation";
CREATE TRIGGER "im_conversation__upd_time" BEFORE UPDATE ON "im_conversation" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();

-- ----------------------------
-- Table structure for im_message
-- ----------------------------
CREATE TABLE IF NOT EXISTS "im_message" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "conversation_id" bigint NOT NULL,
  "sender_id" varchar(32) NOT NULL,
  "type" smallint NOT NULL,
  "content" text NOT NULL,
  "file_id" varchar(32) NULL DEFAULT NULL,
  "is_withdrawn" boolean NULL DEFAULT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) NULL DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "im_message" IS 'IM-消息表';
COMMENT ON COLUMN "im_message"."id" IS 'ID';
COMMENT ON COLUMN "im_message"."conversation_id" IS '会话ID';
COMMENT ON COLUMN "im_message"."sender_id" IS '发送用户ID';
COMMENT ON COLUMN "im_message"."type" IS '类型：1-文本/2-图片/3-视频/4-文件';
COMMENT ON COLUMN "im_message"."content" IS '消息内容';
COMMENT ON COLUMN "im_message"."file_id" IS '附件ID';
COMMENT ON COLUMN "im_message"."is_withdrawn" IS '是否撤回';
COMMENT ON COLUMN "im_message"."crt_time" IS '创建时间';
COMMENT ON COLUMN "im_message"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "im_message"."crt_name" IS '创建用户';
COMMENT ON COLUMN "im_message"."crt_host" IS '创建IP';
COMMENT ON COLUMN "im_message"."deleted" IS '是否删除';

-- ----------------------------
-- Table structure for im_message_read
-- ----------------------------
CREATE TABLE IF NOT EXISTS "im_message_read" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "message_id" bigint NOT NULL,
  "user_id" varchar(32) NOT NULL,
  "read_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "im_message_read" IS 'IM-消息已读状态表';
COMMENT ON COLUMN "im_message_read"."id" IS 'ID';
COMMENT ON COLUMN "im_message_read"."message_id" IS '消息ID';
COMMENT ON COLUMN "im_message_read"."user_id" IS '用户ID';
COMMENT ON COLUMN "im_message_read"."read_at" IS '读取时间';
CREATE UNIQUE INDEX "uk_msg_user" ON "im_message_read" ("message_id", "user_id");
COMMENT ON INDEX "uk_msg_user" IS '用户已读消息关联';

-- ----------------------------
-- Table structure for im_participant
-- ----------------------------
CREATE TABLE IF NOT EXISTS "im_participant" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "conversation_id" bigint NOT NULL,
  "user_id" varchar(32) NOT NULL,
  "last_read_message_id" bigint NULL DEFAULT NULL,
  "unread_count" integer NULL DEFAULT NULL,
  "title" varchar(255) NULL DEFAULT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "im_participant" IS 'IM-会话参与者表';
COMMENT ON COLUMN "im_participant"."id" IS 'ID';
COMMENT ON COLUMN "im_participant"."conversation_id" IS '会话ID';
COMMENT ON COLUMN "im_participant"."user_id" IS '用户ID';
COMMENT ON COLUMN "im_participant"."last_read_message_id" IS '最后一条已读消息ID';
COMMENT ON COLUMN "im_participant"."unread_count" IS '未读消息数量';
COMMENT ON COLUMN "im_participant"."title" IS '用户标题';
COMMENT ON COLUMN "im_participant"."crt_time" IS '创建时间';
COMMENT ON COLUMN "im_participant"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "im_participant"."crt_name" IS '创建用户';
COMMENT ON COLUMN "im_participant"."crt_host" IS '创建IP';
CREATE UNIQUE INDEX "uk_user_conv" ON "im_participant" ("conversation_id", "user_id");
COMMENT ON INDEX "uk_user_conv" IS '用户参与聊天记录';

